"use client";
import AppHeader from "components/app.header";
import "./globals.css";
import type { Metadata } from "next";
import AppFooter from "components/app.footer";
import StyledComponentsRegistry from "lib/AntdRegistry";
import { Layout } from "antd";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal", "normal", "normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <Layout>
            <AppHeader />
            {children}
            <AppFooter />
          </Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
